### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by carlosjourdan** [CAAPIM/Docker-MAS#45]
I followed all the steps on the ReadMe.md and got the images running. However, when trying to access, I get an internal server error with the following messages on the console. Any idea on how to get arround that?

Best regards,
Carlos Jourdan

```

mas_1                | Jan 02, 2018 5:34:31 PM com.l7tech.server.SoapMessageProcessingServlet serviceNoAudit
mas_1                | WARNING: Published service message input is not licensed 'The specified feature is not supported on this Gateway: service:HttpMessageInput.'.
mas_1                | Jan 02, 2018 5:34:31 PM org.apache.catalina.core.ApplicationDispatcher invoke
mas_1                | SEVERE: Servlet.service() for servlet SoapMessageProcessingServlet threw exception
mas_1                | java.lang.NullPointerException
mas_1                |  at com.l7tech.server.audit.AuditContextImpl.a(Unknown Source)
mas_1                |  at com.l7tech.server.audit.AuditContextFactory.doWithNewAuditContext(Unknown Source)
mas_1                |  at com.l7tech.server.SoapMessageProcessingServlet.service(Unknown Source)
mas_1                |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:342)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
mas_1                |  at com.l7tech.server.transport.http.HttpNamespaceFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.WsdlFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.ConnectionIdFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.InputTimeoutFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.log.HybridDiagnosticContextServletFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
mas_1                |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:181)
mas_1                |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
mas_1                |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
mas_1                |  at com.l7tech.server.tomcat.ResponseKillerValve.invoke(Unknown Source)
mas_1                |  at com.l7tech.server.tomcat.ConnectionIdValve.invoke(Unknown Source)
mas_1                |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
mas_1                |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:295)
mas_1                |  at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
mas_1                |  at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
mas_1                |  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:396)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
mas_1                |  at java.lang.Thread.run(Thread.java:745)
mas_1                |
mas_1                | Jan 02, 2018 5:34:31 PM org.apache.catalina.core.StandardWrapperValve invoke
mas_1                | SEVERE: Servlet.service() for servlet default threw exception
mas_1                | java.lang.NullPointerException
mas_1                |  at com.l7tech.server.audit.AuditContextImpl.a(Unknown Source)
mas_1                |  at com.l7tech.server.audit.AuditContextFactory.doWithNewAuditContext(Unknown Source)
mas_1                |  at com.l7tech.server.SoapMessageProcessingServlet.service(Unknown Source)
mas_1                |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:342)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
mas_1                |  at com.l7tech.server.transport.http.HttpNamespaceFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.WsdlFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.ConnectionIdFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.InputTimeoutFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.log.HybridDiagnosticContextServletFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
mas_1                |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:181)
mas_1                |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
mas_1                |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
mas_1                |  at com.l7tech.server.tomcat.ResponseKillerValve.invoke(Unknown Source)
mas_1                |  at com.l7tech.server.tomcat.ConnectionIdValve.invoke(Unknown Source)
mas_1                |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
mas_1                |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:295)
mas_1                |  at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
mas_1                |  at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
mas_1                |  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:396)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
mas_1                |  at java.lang.Thread.run(Thread.java:745)
mas_1                |
mas_1                | Jan 02, 2018 5:34:31 PM com.l7tech.server.SoapMessageProcessingServlet serviceNoAudit
mas_1                | WARNING: Published service message input is not licensed 'The specified feature is not supported on this Gateway: service:HttpMessageInput.'.
mas_1                | Jan 02, 2018 5:34:31 PM org.apache.catalina.core.ApplicationDispatcher invoke
mas_1                | SEVERE: Servlet.service() for servlet SoapMessageProcessingServlet threw exception
mas_1                | java.lang.NullPointerException
mas_1                |  at com.l7tech.server.audit.AuditContextImpl.a(Unknown Source)
mas_1                |  at com.l7tech.server.audit.AuditContextFactory.doWithNewAuditContext(Unknown Source)
mas_1                |  at com.l7tech.server.SoapMessageProcessingServlet.service(Unknown Source)
mas_1                |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:342)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
mas_1                |  at com.l7tech.server.transport.http.HttpNamespaceFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.WsdlFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.ConnectionIdFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.InputTimeoutFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.log.HybridDiagnosticContextServletFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
mas_1                |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:181)
mas_1                |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
mas_1                |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
mas_1                |  at com.l7tech.server.tomcat.ResponseKillerValve.invoke(Unknown Source)
mas_1                |  at com.l7tech.server.tomcat.ConnectionIdValve.invoke(Unknown Source)
mas_1                |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
mas_1                |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:295)
mas_1                |  at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
mas_1                |  at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
mas_1                |  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:396)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
mas_1                |  at java.lang.Thread.run(Thread.java:745)
mas_1                |
mas_1                | Jan 02, 2018 5:34:31 PM org.apache.catalina.core.StandardWrapperValve invoke
mas_1                | SEVERE: Servlet.service() for servlet default threw exception
mas_1                | java.lang.NullPointerException
mas_1                |  at com.l7tech.server.audit.AuditContextImpl.a(Unknown Source)
mas_1                |  at com.l7tech.server.audit.AuditContextFactory.doWithNewAuditContext(Unknown Source)
mas_1                |  at com.l7tech.server.SoapMessageProcessingServlet.service(Unknown Source)
mas_1                |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:342)
mas_1                |  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
mas_1                |  at com.l7tech.server.transport.http.HttpNamespaceFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.WsdlFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.ConnectionIdFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.transport.http.InputTimeoutFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at com.l7tech.server.log.HybridDiagnosticContextServletFilter.doFilter(Unknown Source)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
mas_1                |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
mas_1                |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
mas_1                |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:181)
mas_1                |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
mas_1                |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
mas_1                |  at com.l7tech.server.tomcat.ResponseKillerValve.invoke(Unknown Source)
mas_1                |  at com.l7tech.server.tomcat.ConnectionIdValve.invoke(Unknown Source)
mas_1                |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
mas_1                |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:295)
mas_1                |  at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
mas_1                |  at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
mas_1                |  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:396)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
mas_1                |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
mas_1                |  at java.lang.Thread.run(Thread.java:745)
```

**Comment by carlosjourdan** [comment]
Seems somewhat related to this [kb](https://support.ca.com/us/knowledge-base-articles.TEC1785955.html)...

**Comment by sunsh06** [comment]
@carlosjourdan The image you pulled has been deprecated. Please re-sync with the master branch of this repo to make sure the image you pulled is up-to-date.
